name = "enigma-syndicate"
main = "index.js"
compatibility_date = "2024-07-30"

[vars]
YOUR_FIREBASE_JSON_BASE64 = "YOUR_BIG_BASE64_HERE"
OPENAI_API_KEY = "sk-..."

[build]
command = "npx wrangler deploy"

[triggers]
# If you’re using GitHub actions
upload_on_change = true

[observability.logs]
enabled = true


