name = "enigma-syndicate"
main = "index.js"
compatibility_date = "2024-07-30"

[vars]
YOUR_FIREBASE_JSON_BASE64 = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2FuZGJveC1tYWZpYSIsCiAg..."

[build]
command = "npx wrangler deploy"

[observability.logs]
enabled = true 


